/**
 * uMMORPG extract catalog for Forge (forge.grudge-studio.com).
 * Generated by ObjectStore/scripts/build-ummorpg-forge-catalog.mjs
 * Source vault: Desktop/FRESH GRUDGE — no Unity Editor required for regen.
 *
 * Load JSON from /data/ummorpg-*.json (public) or ObjectStore API.
 */

export const UMMORPG_OBJECTSTORE = {
  index: "https://objectstore.grudge-studio.com/api/v1/ummorpg-extract-index.json",
  skills: "https://objectstore.grudge-studio.com/api/v1/ummorpg-skills-for-forge.json",
  placeables: "https://objectstore.grudge-studio.com/api/v1/ummorpg-placeables-for-forge.json",
  bestPractices: "https://objectstore.grudge-studio.com/api/v1/ummorpg-extract-index.json",
} as const;

export const UMMORPG_LOCAL_DATA = {
  skills: "/data/ummorpg-skills.json",
  placeables: "/data/ummorpg-placeables.json",
} as const;

export type UmmorpgSkill = {
  id: string;
  name: string;
  category: string;
  castTime: number | null;
  cooldown: number | null;
  castRange: number | null;
  manaCost: number | null;
  damage: number | null;
  requiredWeaponCategory: string | null;
  unityAsset: string;
};

export type UmmorpgPlaceable = {
  id: string;
  label: string;
  group: string;
  modelUrl: string | null;
  iconUrl: string;
  meshStatus: string;
  forge: { spawnable: boolean; source: string };
};

/** Fetch placeables (prefer same-origin public data, fall back to ObjectStore). */
export async function fetchUmmorpgPlaceables(
  init?: RequestInit,
): Promise<{ count: number; spawnable: number; items: UmmorpgPlaceable[] } | null> {
  for (const url of [UMMORPG_LOCAL_DATA.placeables, UMMORPG_OBJECTSTORE.placeables]) {
    try {
      const r = await fetch(url, init);
      if (!r.ok) continue;
      const j = (await r.json()) as { count: number; spawnable: number; items: UmmorpgPlaceable[] };
      if (j?.items) return j;
    } catch {
      /* try next */
    }
  }
  return null;
}

export async function fetchUmmorpgSkills(
  init?: RequestInit,
): Promise<{ count: number; skills: UmmorpgSkill[] } | null> {
  for (const url of [UMMORPG_LOCAL_DATA.skills, UMMORPG_OBJECTSTORE.skills]) {
    try {
      const r = await fetch(url, init);
      if (!r.ok) continue;
      const j = (await r.json()) as { count: number; skills: UmmorpgSkill[] };
      if (j?.skills) return j;
    } catch {
      /* try next */
    }
  }
  return null;
}

/** Spawnable placeables only (CDN mesh ready). */
export function filterSpawnablePlaceables(items: UmmorpgPlaceable[]): UmmorpgPlaceable[] {
  return items.filter((i) => i.forge?.spawnable && !!i.modelUrl);
}

/** Map weapon-category skills toward Warlords hotbar packs. */
export function skillsForWeaponCategory(
  skills: UmmorpgSkill[],
  weapon: string,
): UmmorpgSkill[] {
  const w = weapon.toLowerCase();
  return skills.filter(
    (s) =>
      (s.requiredWeaponCategory && s.requiredWeaponCategory.toLowerCase().includes(w)) ||
      s.category === "weapon" ||
      (s.folder && s.folder.toLowerCase().includes(w)),
  );
}

// Generated snapshot sizes (for agent sanity checks)
export const UMMORPG_CATALOG_META = {
  generatedAt: "2026-08-02T03:40:45.014Z",
  placeableCount: 118,
  placeableSpawnable: 111,
  skillCount: 134,
  unitySource: "C:/Users/nugye/Desktop/FRESH GRUDGE/Assets/uMMORPG",
} as const;
